# Generated by Django 3.1.1 on 2020-09-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cached_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
